#!/bin/sh


case `uname -a` in
Linux*x86_64*)  echo "Linux 64 bit"
    google-chrome --app="$1" --user-data-dir=$2
    ;;

Linux*i686*)  echo "Linux 32 bit"
    google-chrome --app="$1" --user-data-dir=$2
    ;;

Darwin*)  echo  "OSX"
	sleep 2
    /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app="$1"
    ;;


*) echo "Google chrome for your os not found!"
   ;;
esac
